### ISSUE TITLE
Need support for Linux Mint 20 Ulyana

### ISSUE THREAD

**Issue by shemed-blackops** [AdnanHodzic/displaylink-debian#438] opened 2020-07-12 19:34 UTC
Hello.
I need support for Linux Mint 20 "ulyana"

sudo ./displaylink-debian.sh --debug
cat: /sys/devices/evdi/version: No such file or directory

**Comment by Barabas-dev** [comment] 2020-07-17 16:17
Duplicate of #435

**Closed** 2020-07-18 18:36 UTC
Labels: duplicate
